[package]
name = "lapce-go"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.22"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
lapce-plugin = { git = "https://github.com/lapce/lapce-plugin-rust", branch = "master" }
