name = "lapce-go"
display-name = "Go"
description = "Go for Lapce: powered by Gopls"
version = "0.1.1"
author = "Lapce"
repository = "lapce/lapce-go"
wasm = "lapce-go.wasm"

[configuration]
language_id = "go"
env_command = "go env"
system_lsp = true
[configuration.options.binary]
args = [
    "-rpc.trace",
    "-logfile=gopls-logfile.txt"
]
[configuration.options]
semanticTokens = true
